fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
  symlinks:
    packetbeat: "#{source_dir}"
