require: rubocop-rspec
AllCops:
  Include:
    - ./**/*.rb
  Exclude:
    - files/**/*
    - vendor/**/*
    - .vendor/**/*
    - pkg/**/*
    - spec/fixtures/**/*
Metrics/BlockLength:
  Enabled: False

Style/AutoResourceCleanup:
  Enabled: True

Style/CollectionMethods:
  Enabled: True

Style/DocumentationMethod:
  Enabled: True

Naming/FileName:
  Exclude:
    - Rakefile
    - Gemfile

Layout/FirstArrayElementLineBreak:
  Enabled: True

Layout/FirstHashElementLineBreak:
  Enabled: True

Layout/FirstMethodArgumentLineBreak:
  Enabled: True

Layout/FirstMethodParameterLineBreak:
  Enabled: True

Style/ImplicitRuntimeError:
  Enabled: True

Style/MethodCalledOnDoEndBlock:
  Enabled: True

Layout/MultilineAssignmentLayout:
  Enabled: True

Style/OptionHash:
  Enabled: True

Style/Send:
  Enabled: True

Style/SingleLineBlockParams:
  Enabled: True

Style/StringMethods:
  Enabled: True

Style/SymbolArray:
  Enabled: True

Style/Encoding:
  Enabled: True

# RSpec

# We don't use rspec in this way
RSpec/DescribeClass:
  Enabled: False

# Example length is not necessarily an indicator of code quality
RSpec/ExampleLength:
  Enabled: False

RSpec/NamedSubject:
  Enabled: False

# disabled for now since they cause a lot of issues
# these issues aren't easy to fix
RSpec/RepeatedDescription:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False
