---
before_install:
  - gem update --system
  - gem --version
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.0
script:
  - "bundle exec rake validate test SPEC_OPTS='--format documentation'"
