---
before_install:
  - gem update --system
  - gem --version
cache: bundler
language: ruby
rvm:
  - 2.1.9
    bundler_args: --without development
  - 2.2.5
    bundler_args: --without development
script:
  - "bundle exec rake validate test SPEC_OPTS='--format documentation'"
